# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
